
---
Title: Econometrics II 
Author: Dr. Edmundo Molina 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem Set 1

# Instructions  
Fell free to work in groups while solving this assignment. However, submissions are only allowed in pairs. The inbox for team submissions will be available in Canvas. Please make your write-ups are readable. In particular for the empirical questions, include the statistical results necessary to answer the questions. Make the response self-contained. 

##### Total Points: 100 
##### Due Date: February 6th, 2025

# Part 1 (20 points)
#### The intentions of these questions is to give you practice deriving simple results about the different models we are discussing in class. Consider the "constant" regression model: 

$$ Y_{i}=\alpha + \epsilon_{i}$$

#### Derive the OLS (ordinary least squares) estimators of $\alpha $ by setting up the minimization problem and solving for $\hat{\alpha}$ that minimizes the sum of squared residuals. Interpret this formula

# Part 2 (10 points)

#### True/False:  If the statement is false, provide a one sentence explanation why it is false (25 points).

##### 1.Under the assumption of no selection on unobservables, least regression is a solution to the "curse of dimensionality" that is valid under additional assumptions between the observables and the dependent variable

##### 2.	The "treatment effect" of T, a 0-1 condition that is randomly assigned to a sample of individuals, is define as the difference in the average outcome of the individuals with T=1 and individuals with T= 0

##### 3.	The "intent to treat" effect is in general not the same as the "average treatment effect" because of non-compliance with treatment (where noncompliance occurs when individuals who are randomized do not receive the treatment, do get it)

##### 4. The Central Limit Theorem says that with a same where the observations are independent of each other and have the same expected value $\bar{Y}_{N}$  the sample mean for a sample size N, will have an exact normal distribution.

##### 5. Evidence from a well-implemented randomized experiment (successful randomization, no attrition, perfect compliance) cannot identify the fraction of participants who experience a gain from a program (i.e. policy intervention)

# Part 3 (10 points)

### Reasoning questions

You are interested in understanding the male-female wage gap. You have a dataset of a large sample of workers which contains information on three (and only three) worker characteristics: wages measured in dollars, gender, and education. You first regress on 2 variables: a) a constant, and b) an indicator variable for being a woman, and find that the coefficient on the women's indicator variable is -2.0. You also notice that men and women have similar levels of education, and that better educated workers earn much higher wages that poorly educated workers. (25 points)


##### a.	Provide a one sentence interpretation of the coefficient of the female indicator variable

##### b.	Is there "selection on observables"? Why or why not?

##### c.	Suppose you added education as a control variable in the regression. What effect(s) might this have on the standard error of the estimated coefficient on the female indicator variable?

# Part 4 (30 points)

For this section questions use the dataset smoking2.dta (available on Canvas). This is a dataset comprised of birth certificate records. It contains information on infant health, demographic characteristics of the parents, pre-natal care use, and health risks factors.

### 1. Suppose your goal was to determine the impact of smoking during pregnancy on a measure of infant health, birthweight. 

#### a. Compare the average birthweight (i.e. dbirwt) of children born to smokers and non-smokers (i.e. tobacco). Is the mean difference "significant" in a statistical sense?


#### b.	Test for "selection on observables". Remember to check whether both conditions of selection on observables are met. What does this suggest about the results from (a) being a valid causal estimate of the effect of smoking on birthweight?

#### c. Based on your tests in (b), briefly describe the socioeconomic status of smokers compared to non-smokers (i.e. these include variables: tobacco,dmage,dmeduc,dmar, dlivord,nprevist,disllb,dfage,dfeduc,anemia,diabete,phyper , pre4000,preterm,alcohol, drink,foreignb,plural,deadkids,mblack,motherr, mhispan,fblack,fotherr,fhispan).

#### d. Given the available information in the dataset, do you think "selection on unobservables" may pose a problem (HINT: use the residuals() function )?

### 2. Now see if the estimated "effect" of smoking is affected by controlling for observable characteristics in an OLS regression. This procedure is known as "regression adjusting" the difference in means. (25 points)

#### a. First, control for a limited set of demographic characteristics such as race and age. What happens to the coefficient on the smoking indicator variable?

#### b. Now include other controls for other characteristics such as education, prenatal care utilization, and other behavioral risk factors like alcohol consumption. What happens to the "effect" of smoking? What does the p-values indicate with respect to the hypothesis that the coefficients on all of the covariates you just added are zero.

#### c.	Finally, include controls for other medical risk factors such as the mother's hypertension. What happens to the effect of smoking?

#### d.BRIEFLY explain why adding these controls may be inappropriate.


# Part 5 (30 points)

These questions ask you to analyze a data set with information that was collected as part of the randomized evaluation of the US Federal Job Corps Program. Before getting started, read the description of the program in Schochet, Peter, John Burghardt and Sheena McConnell. 2008. "Does Job Corps Work? Impact Findings from the National Job Corps Study." American Economic Review, 98(5).  The data set is called jobcorps.dta and is located in Canvas 

#### a. Assess the success of randomization. Using the t.test command, test whether the difference in the fraction male was different in the experimental (treatmnt==1) and control group (treatmnt==0). What does this suggest? 

#### b. Conduct similar tests of the randomization using other variables [Hint: be careful about the observable characteristics that you analyze]

#### c. Another way to test the randomization is by seeing how closely the observable characteristics can predict whether someone is in the experimental group or the control group. One way to implement this test is by running the following regression: 

#### d.What is your overall impression from these results? Was the randomization successful? [limit your discussion to about 3 sentences] 

#### e. A serious problem that often arises during randomized evaluation is sample attrition. Compare the characteristics of individuals who drop out of the sample and those that complete the 48 month follow-up (attrit=0). Does it appear as though there is systematic attrition, or does it appear as though attrition is not systematically related to observables? 

#### f. Briefly (1-2 sentences) explain why attrition complicates estimation of experimental impacts, even with successful randomization. 

#### g. Propose a strategy for testing whether attrition is likely to pose a problem for this randomized evaluation.

#### h. Implement your proposed test using the job corps data. Does it appear that attrition is a problem? 

#### i. For the rest of the questions, only use individuals who complete the 48 month follow-up. Use the subset() function to retain only the data points for which attrit==0. Estimate the experimental impact on earnings in the first quarter after random assignment and test whether the estimated impacts are statistically distinguishable from zero. 

#### j. Given the structure of the Job Corps program, provide an explanation for this result. 

#### k. Now estimate the experimental impact on earnings in quarters 2-16 after random assignment. What does these result suggest about the time-profile of the effect of being in the Job Corps program? [It may be useful to plot the estimated effect as a function of time]

#### l. Another serious problem in randomized evaluations is that key variables are, for some reason, missing. Using a similar strategy to that proposed in g, test whether missing data is likely to be a serious problem in the Jops Cops evaluation. 
